#!/bin/sh

# ====================================
# Install packages
# ====================================

read -p 'Install virtualbox additions? (y/N): ' choice

if [ "$choice" = "y" ]; then
    sudo pacman -S xf86-video-vmware virtualbox-guest-utils virtualbox-guest-modules-arch --noconfirm --needed
fi

sudo pacman -S feh rofi ranger sxhkd dunst neofetch noto-fonts noto-fonts-emoji ttf-font-awesome otf-font-awesome pulseaudio pulseaudio-alsa pamixer unzip picom evince light maim w3m numlockx openssh telegram-desktop xclip wmname blueberry --noconfirm --needed


if pacman -Qs yay > /dev/null ; then
    echo "Yay is already installed, moving on..."
else
    mkdir -p ~/sources
    cd ~/sources
    rm -rf yay
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ~
fi


yay -S bspwm-rounded-corners rxvt-unicode-256xresources polybar spicetify-cli nerd-fonts-iosevka python-ueberzug spotify betterlockscreen-git gotop xcwd-git pulseaudio-ctl hardcode-tray batsignal --needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm

sudo pacman -S debtap
sudo debtap -u

# tabbed extension for urxvt
curl https://raw.githubusercontent.com/mina86/urxvt-tabbedex/master/install | sh


# ====================================
# Nvidia discrete card  (Xserver setup for multi-monitor)
# source: https://us.download.nvidia.com/XFree86/Linux-x86_64/450.57/README/randr14.html
# ====================================

sudo pacman -S nvidia nvidia-prime bbswitch
# sudo cp ~/.config/yadm/xorg.conf.d/10-external_hdmi.conf /etc/X11/xorg.conf.d/10-gpu.conf
yay -S optimus-manager # if problem occurs, delete /etc/X11/xorg.conf and /etc/X11/xorg.conf.d/*
sudo cp ~/.config/yadm/optimus-manager.conf /etc/optimus-manager/optimus-manager.conf

# ====================================
# Download and set background
# ====================================

mkdir -p ~/Documents/Wallpapers &> /dev/null
curl https://i.imgur.com/XCaXGFB.png > ~/Documents/Wallpapers/gruvbox.png

# ====================================
# Polybar font
# ====================================

mkdir -p ~/.local/share/fonts &> /dev/null
curl https://raw.githubusercontent.com/adi1090x/polybar-themes/master/polybar-8/fonts/icomoon-feather.ttf > icomoon-feather.ttf
mv icomoon-feather.ttf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/

# ====================================
# Powerline arrow fix
# ====================================

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/
mkdir -p ~/.config/fontconfig
mkdir -p ~/.config/fontconfig/conf.d
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

# ====================================
# Icon theme
# ====================================
wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR="$HOME/.icons" sh
sudo hardcode-tray --size 24 --theme Papirus

echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ feh --bg-fill ~/Documents/Wallpapers/wallpaper.png"
