#!/bin/sh
set -e
# ====================================
# Install packages
# ====================================

sudo pacman -S --noconfirm --needed \
    zsh ranger \
    btop unzip \
    openssh pacman-contrib \
	zoxide fzf

# ranger plugins
git clone git@github.com:jchook/ranger-zoxide.git ~/.config/ranger/plugins/zoxide
git clone git@github.com:joouha/ranger_tmux.git ~/.config/ranger/plugins/ranger_tmux

# tmux plugins
git clone git@github.com:wfxr/tmux-net-speed.git ~/.config/tmux/tmux-net-speed
git clone git@github.com:tmux-plugins/tmux-prefix-highlight.git ~/.config/tmux/tmux-prefix-highlight

if pacman -Qs paru > /dev/null ; then
    echo "Paru is already installed, moving on..."
else
    mkdir -p ~/sources/compiled_from_source
    cd ~/sources/compiled_from_source
    rm -rf paru
    git clone https://aur.archlinux.org/paru-bin.git
    cd paru
    makepkg -si --noconfirm
    cd ~
fi

paru -S --needed --noconfirm \
    nvim-packer-git paccache-hook

# ====================================
# oh-my-zsh
# ====================================
yes | sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
for theme in `ls *.zsh-theme`; do
	ln -s -r ~/.config/yadm/$theme ~/.oh-my-zsh/custom/themes/$theme
done

echo "=============="
echo "==== DONE ===="
echo "=============="
