[mgr]
#linemode = "size"
linemode = "size_and_mtime"
mouse_events = [] # disabled

[open]
rules = [
  # Folder
  { mime = "inode/directory", use = [ "open", "reveal", "code" ] },
  # Empty file
  { mime = "inode/empty", use = [ "edit", "reveal" ] },
  # Text file
  { mime = "text/*", use = [ "edit", "reveal" ] },
  # Other text files
  { mime = "application/octet-stream", use = [ "edit", "reveal" ] }, 
  # Fallback
  { name = "*", use = [ "open", "reveal" ] },
]

[opener]
code = [ { run = 'code "$@"' } ]

[plugin]
prepend_previewers = [
  { mime = "application/octet-stream", run = "code" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "mime"
if   = "!mime"
name = "*"
run  = "mime-ext"
prio = "high"
