#! /bin/sh

is_external_monitor_present=$(xrandr --query | grep '^DP1 connected')
if [[ $is_external_monitor_present ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output DP1 --mode 1920x1080 --rotate normal --left-of eDP1
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc monitor DP1 -d 6 7 8 9 10
    bspc wm -O eDP1 DP1
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    ~/.local/bin/floating_ws_5.sh & # any windows in WS 5 will be floating
fi

sxhkd &

bspc rule -a URxvt:scratchy state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc rule -a Chromium desktop='^1' follow=true border=false

bspc rule -a jetbrains-pycharm follow=true border=false state=floating
bspc rule -a jetbrains-webstorm follow=true border=false
bspc rule -a "MATLAB R2019b - academic use" desktop='^5' follow=true border=false
bspc rule -a MATLABWindow desktop='^5' follow=true border=false center=true

bspc rule -a TelegramDesktop desktop='^7' state=floating center=true follow=true border=false
bspc rule -a discord desktop='^8' state=floating center=true follow=true border=false


bspc config border_width          2
bspc config border_radius         6
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Documents/Wallpapers/dawn.jpg
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Documents/Wallpapers/wolf_moon.jpg

# ------- Autostart apps ------
# Picom (compositor)
picom --xrender-sync-fence &

# Dunst (notifications)
killall -q dunst
dunst &

# Nm-applet
#nm-applet &

# Blue-light dimmer
killall -q redshift
#while pgrep -u $UID -x redshift > /dev/null; do sleep 1; done
redshift &

# Battery status notifications
killall -q batsignal
batsignal -n BAT1 -w 20 -c 10 -b

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
libinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
#xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Click Method Enabled" 0 1
#xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Disable While Typing Enabled" 0

# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
# setxkbmap -option caps:escape
setxkbmap -layout it

# Fix for Jetbrains IDEs
wmname LG3D

# allow Docker to open X11 windows
xhost +local:docker

